// import localFont from "next/font/local";
import "./globals.css";
import { Dongle } from 'next/font/google';


const dongle = Dongle({
  weight: ['300', '400', '700'], // You must specify at least one of these
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dongle', // Creates a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dongle.variable} ${dongle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
